export const dom ={
    //hours
    hours_rightBtn:document.querySelector(`.two_btn .right`),
    hours_leftBtn:document.querySelector(`.two_btn .left`),
    hours_move:document.querySelector('.see ul'),
    //main_body
    body_wind:document.querySelector('.wind'),
    body_windIcon:document.querySelector('.wind_before'),
    body_aimUl:document.querySelector('.seven_day ul'),
    body_Ctx:document.getElementById('myChart'),
    body_tempWeather:document.querySelector('.weather15d'),
    daily_leftBtn:document.querySelector('.daily_left'),
    daily_rightBtn: document.querySelector('.daily_right'),
    daily_move:document.querySelector('.daily_index ul'),
    daily_add:document.querySelector('.daily_index .window ul'),
    //nav_bottom
    bot_push:document.querySelector('.push_time'),
    bot_nowTemp:document.querySelector('.now_temp'),
    bot_weather:document.querySelector(`.weather_name`),
    bot_icon:document.querySelector('.now_icon'),
    bot_humi:document.querySelector('.humidity'),
    bot_kPa:document.querySelector('.kPa'),
    bot_warning: document.querySelector('.warning'),
    bot_addStyle:document.createElement('style'),
    bot_nowAQI:document.querySelector('.now_aqi span'),
    bot_head:document.querySelector('.airtitle'),
    bot_pm25:document.querySelector('.pm25'),
    bot_pm10:document.querySelector('.pm10'),
    bot_so2:document.querySelector('.so2'),
    bot_no2:document.querySelector('.no2'),
    bot_o3:document.querySelector('.o3'),
    bot_co:document.querySelector('.co'),
    //nav
    exitBtn:document.querySelector('.exit'),
    nav_searchCity:document.querySelector(`.search_city`),
    nav_searchList:document.querySelector(`.search_list`),
    nav_searchListUl:document.querySelector(`.search_list ul`),
    nav_hotCity:document.querySelector('.hot_city'),
    nav_navP:document.querySelector('.nav_p'),
    nav_concernBtn:document.querySelector('.nav_a:last-of-type'),
    nav_fullCity:document.querySelector(`.full_city`),
    nav_concernLi:document.querySelector(`.concern ul`),
    nav_history:document.querySelector('.history'),
    nav_clearBtn:document.querySelector('.btn'),
    nav_historyUl:document.querySelector('.history ul'),
}